// require('zepto/zepto')

// require('a0-angular-storage/dist/angular-storage.js')
require('angucomplete-alt/angucomplete-alt.js')
require('angular-cookies/angular-cookies.js')
require('angular-dropdowns/dist/angular-dropdowns.js')
require('angular-ellipsis/src/angular-ellipsis.js')
require('angular-filter/dist/angular-filter.min.js')
require('angular-img-fallback/angular.dcb-img-fallback.js')
require('intro.js/intro.js')
// require('angular-intro.js/src/angular-intro.js')
require('angular-jwt/dist/angular-jwt.js')
require('angular-messages/angular-messages.js')
require('angular-sanitize/angular-sanitize.js')
// require('x2js/xml2json.min.js')
// require('angular-xml/angular-xml.js')
require('angular-animate/angular-animate.js')
require('angularjs-toaster/toaster.js')
require('appirio-tech-ng-iso-constants/dist/ng-iso-constants.js')
require('d3/d3.js')
require('jstzdetect/jstz.min.js')
require('moment/moment.js')
require('ng-busy/build/angular-busy.js')
require('ng-notifications-bar/dist/ngNotificationsBar.min.js')
require('ngDialog/js/ngDialog.js')
// require('lodash/lodash.js')

require('angular-touch/angular-touch.js')
require('angular-carousel/dist/angular-carousel.js')
require('matchmedia/matchMedia.js')
require('ngSticky/lib/sticky.js')
// require('../assets/scripts/auth0-angular.js')
// require('../assets/scripts/auth0.js')
require('../assets/scripts/moment-timezone-with-data-2010-2020.js')

// require('angular-resource/angular-resource')
require('angular-sanitize/angular-sanitize')

// require('angular-scroll/angular-scroll')

// require('auth0-angular/build/auth0-angular')
require('angular-storage')
require('angular-jwt')
require('ngReact')

window.classNames = require('classnames')
window.React = require('react')
window.AutosizeInput = require('react-input-autosize')
window.moment = require('moment')
window.Select = require('react-select')

// require('appirio-tech-ng-ui-components/dist/main')
// require('appirio-tech-ng-ui-components/dist/main.css')
require('react-select/dist/react-select.css')
