require('zepto/zepto')
require('angular')

require('a0-angular-storage/dist/angular-storage.js')
require('angucomplete-alt/angucomplete-alt.js')
require('angular-cookies/angular-cookies.js')
require('angular-dropdowns/dist/angular-dropdowns.js')
require('angular-ellipsis/src/angular-ellipsis.js')
require('angular-filter/dist/angular-filter.min.js')
require('angular-img-fallback/angular.dcb-img-fallback.js')
require('intro.js/intro.js')
// require('angular-intro.js/src/angular-intro.js')
require('angular-jwt/dist/angular-jwt.js')
require('angular-messages/angular-messages.js')
require('angular-sanitize/angular-sanitize.js')
require('angular-ui-router/release/angular-ui-router.js')
// require('x2js/xml2json.min.js')
// require('angular-xml/angular-xml.js')
require('angular-animate/angular-animate.js')
require('angularjs-toaster/toaster.js')
require('appirio-tech-ng-iso-constants/dist/ng-iso-constants.js')
require('d3/d3.js')
require('jstzdetect/jstz.min.js')
require('moment/moment.js')
require('ng-busy/build/angular-busy.js')
require('ng-notifications-bar/dist/ngNotificationsBar.min.js')
require('ngDialog/js/ngDialog.js')
require('lodash/lodash.js')
require('restangular/dist/restangular.js')
require('angular-touch/angular-touch.js')
require('angular-carousel/dist/angular-carousel.js')
require('matchmedia/matchMedia.js')
require('ngSticky/lib/sticky.js')
require('../assets/scripts/auth0-angular.js')
require('../assets/scripts/auth0.js')
require('../assets/scripts/moment-timezone-with-data-2010-2020.js')

// require('angular-resource/angular-resource')
require('angular-sanitize/angular-sanitize')
require('angular-ui-router')
// require('angular-scroll/angular-scroll')

// require('auth0-angular/build/auth0-angular')
require('angular-storage')
require('angular-jwt')
require('ngReact')

window.classNames = require('classnames')
window.React = require('react')
window.AutosizeInput = require('react-input-autosize')
window.moment = require('moment')
window.Select = require('react-select')

require('./account/account.module')
require('./account/account.routes')
require('./account/login/login.controller')
require('./account/logout/logout.controller')
require('./account/register/register.controller')
require('./account/reset-password/reset-password.controller')
require('./blocks/exception/exception.module')
require('./blocks/exception/exception')
require('./blocks/exception/exception-handler.provider')
require('./blocks/logger/logger.module')
require('./blocks/logger/logEnhancer')
require('./blocks/logger/logger')
require('./community/community.module')
require('./community/community.routes')
require('./community/members.controller')
require('./community/statistics.controller')
require('./directives/tcui-components.module')
require('./directives/account/toggle-password/toggle-password.directive')
require('./directives/account/toggle-password-with-tips/toggle-password-with-tips.directive')
require('./directives/account/validate-email.directive')
require('./directives/account/validate-register.directive')
require('./directives/badges/badge-tooltip.directive')
require('./directives/busy-button/busy-button.directive')
require('./directives/challenge-links/challenge-links.directive')
require('./directives/challenge-tile/challenge-tile.directive')
require('./directives/challenge-user-place/challenge-user-place.directive')
require('./directives/distribution-graph/distribution-graph.directive')
require('./directives/empty-state-placeholder/empty-state-placeholder.directive')
require('./directives/external-account/external-account.directive')
require('./directives/external-account/external-link-deletion.controller')
require('./directives/external-account/external-links-data.directive')
require('./directives/external-account/external-web-links.directive')
require('./directives/focus-on.directive')
require('./directives/header/header-menu-item.directive')
require('./directives/history-graph/history-graph.directive')
require('./directives/input-sticky-placeholder/input-sticky-placeholder.directive')
require('./directives/ios-card/ios-card.directive')
require('./directives/on-file-change.directive')
require('./directives/onoffswitch/onoffswitch.directive')
require('./directives/page-state-header/page-state-header.directive')
require('./directives/preventEventPropagation.directive')
require('./directives/profile-widget/profile-widget.directive')
require('./directives/responsive-carousel/responsive-carousel.directive')
require('./directives/skill-tile/skill-tile.directive')
require('./directives/slideable.directive')
require('./directives/srm-tile/srm-tile.directive')
require('./directives/tc-endless-paginator/tc-endless-paginator.directive')
require('./directives/tc-paginator/tc-paginator.directive')
require('./directives/tc-section/tc-section.directive')
require('./directives/tc-sticky/tc-sticky.directive')
require('./directives/tc-tabs/tc-tabs.directive')
require('./directives/tc-transclude.directive')
require('./directives/track-toggle/track-toggle.directive')
require('./topcoder.module')
require('./filters/challengeLinks.filter')
require('./filters/deadline-msg.filter')
require('./filters/empty.filter')
require('./filters/external-link-color.filter')
require('./filters/listRoles.filter')
require('./filters/local-time.filter')
require('./filters/location.filter')
require('./filters/npad.filter')
require('./filters/ordinal.filter')
require('./filters/percentage.filter')
require('./filters/rating-color.filter')
require('./filters/role.filter')
require('./filters/ternary.filter')
require('./filters/time-diff.filter')
require('./filters/track.filter')
require('./filters/truncate.filter')
require('./filters/underscore-strip.filter')
require('./filters/url-protocol.filter')
require('./layout/layout.module')
require('./layout/header/header.controller')
require('./my-challenges/my-challenges.module')
require('./my-challenges/my-challenges.controller')
require('./my-challenges/my-challenges.routes')
require('./my-dashboard/my-dashboard.module')
require('./my-dashboard/community-updates/community-updates.controller')
require('./my-dashboard/header-dashboard/header-dashboard.controller')
require('./my-dashboard/my-challenges/my-challenges.controller')
require('./my-dashboard/my-dashboard.controller')
require('./my-dashboard/my-dashboard.routes')
require('./my-dashboard/programs/programs.controller')
require('./my-dashboard/srms/srms.controller')
require('./my-dashboard/subtrack-stats/subtrack-stats.controller')
require('./my-srms/my-srms.controller')
require('./my-srms/my-srms.module')
require('./my-srms/my-srms.routes')
require('./peer-review/peer-review.module')
require('./peer-review/completed-review/completed-review.controller')
require('./peer-review/edit-review/edit-review.controller')
require('./peer-review/peer-review.routes')
require('./peer-review/readOnlyScorecard/readOnlyScorecard.controller')
require('./peer-review/review-status/review-status.controller')
require('./peer-review/review-status/review-status.filter')
require('./profile/profile.module')
require('./profile/about/about.controller')
require('./profile/badges/badges.controller')
require('./profile/profile.controller')
require('./profile/profile.routes')
require('./profile/subtrack/subtrack.controller')
require('./services/services.module')
require('./services/api.service')
require('./services/authtoken.service')
require('./services/blog.service')
require('./services/challenge.service')
require('./services/communityData.service')
require('./services/emptyState.service')
require('./services/externalAccounts.service')
require('./services/externalLinks.service')
require('./services/helpers.service')
require('./services/image.service')
require('./services/introduction.service')
require('./services/jwtInterceptor.service')
require('./services/memberCert.service')
require('./services/nav.service')
require('./services/notification.service')
require('./services/profile.service')
require('./services/review.service')
require('./services/scorecard.service')
require('./services/srm.service')
require('./services/statistics.service')
require('./services/tags.service')
require('./services/tcAuth.service')
require('./services/user.service')
require('./services/userStats.service')
require('./settings/settings.module')
require('./settings/account-info/account-info.controller')
require('./settings/edit-profile/edit-profile.controller')
require('./settings/preferences/preferences.controller')
require('./settings/settings.controller')
require('./settings/settings.routes')
require('./sitemap/sitemap.module')
require('./sitemap/sitemap.routes')
require('./skill-picker/skill-picker.module')
require('./skill-picker/skill-picker.controller')
require('./skill-picker/skill-picker.routes')
require('./submissions/submissions.module')
require('./submissions/submissions.controller')
require('./submissions/submissions.routes')
require('./topcoder.constants')
require('./topcoder.controller')
require('./topcoder.interceptors')
require('./topcoder.routes')
// require('./topcoder.module')
// require('./topcoder.routes')
// require('./topcoder.interceptors')
// require('./topcoder.controller')
// require('./topcoder.constants')
// require('./services/services.module')
// require('./blocks/logger/logger.module')
// require('./blocks/logger/logEnhancer')
// require('./blocks/exception/exception.module')
// require('./layout/layout.module')
// require('./account/account.module')
// require('./peer-review/peer-review.module')
// require('./directives/slideable.directive.js')
// require('./my-dashboard/my-dashboard.module')
// require('./directives/tcui-components.module')
// require('./my-srms/my-srms.module')
// require('./my-challenges/my-challenges.module')
// require('./profile/profile.module')
// require('./settings/settings.module')
// require('./submissions/submissions.module')
// require('./skill-picker/skill-picker.module')
// require('./sitemap/sitemap.module')
// require('./community/community.module')

// require('appirio-tech-ng-ui-components/dist/main')

// require('../assets/css/account')

// require('appirio-tech-ng-ui-components/dist/main.css')
require('react-select/dist/react-select.css')
